spring:
  application:
    name: creditassessor

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-id-address: false
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
