spring:
  application:
    name: creditassessor
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://eureka-user-course:eru-reuesrkeauo-sc@localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-id-address: false
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

mq:
  queue:
    cards-post: cards-post