spring:
  application:
    name: creditassessor
  rabbitmq:
    host: ${RABBITMQ_SERVER}
    port: 5672
    username: guest
    password: guest

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://eureka-user-course:eru-reuesrkeauo-sc@${EUREKA_SERVER}:8761/eureka
  instance:
    hostname: localhost
    prefer-id-address: false
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

mq:
  queue:
    cards-post: cards-post

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/logs-file.log